### PR TITLE
Create new Facebook interview question md file

### PR DESCRIPTION
**Pull request by An-prog-hub**
@rishabh115 please review

### CODE REVIEW

**Comment by An-prog-hub** [comment]
**Please review**

**Review by rishabh115 — CHANGES_REQUESTED** [review]
Hi @An-prog-hub, Formatting is not right. Please look at the contributing guidelines first. I want each articles to be in exact same format.

**Comment by An-prog-hub** [comment]
sure @rishabh115

**Comment by An-prog-hub** [comment]
@rishabh115 I make changes to that please merge that change

**Comment by rishabh115** [comment]
> @rishabh115 I make changes to that please merge that change

Still there are so much formatting issues!

**Pull request closed without merging**
