### PR TITLE
Update Adobe README.md

### PR DESCRIPTION
**Pull request by JoaoVictorNascimento**
added questions in the sections: Data Structures and Algorithms, DBMS,Operating System, Miscellaneous

### CODE REVIEW

**Comment by JoaoVictorNascimento** [comment]
@rishabh115 why did the pull request fail?

**Comment by rishabh115** [comment]
> @rishabh115 why did the pull request fail?

There is an issue with a GitHub action. It isn't failed.

**Comment by JoaoVictorNascimento** [comment]
@rishabh115 Do you have an idea of ​​how to solve it? I believe that others who made a pull request had this same problem.

**Comment by rishabh115** [comment]
Its just a label. Don't be serious about it. Will fix it on Sunday

**Comment by JoaoVictorNascimento** [comment]
@rishabh115
I solved the conflicts and this ready for the merge could take a look. When you approve put the label hacktoberfest-accepted.

**Pull request closed without merging**
